services:
  postgres:
    container_name: postgres-sql-bw
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sudo666
      PGDATA: /var/lib/postgressql/data
      POSTGRES_DB: bookie_world
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bw
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  driver: bridge


volumes:
  postgres:
    driver: local
